// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNGK-dY8wrtuKenmD3gQTcqBzJn9_ssMk',
    appId: '1:851061710789:web:6a8085c02e294abc6535ac',
    messagingSenderId: '851061710789',
    projectId: 'reelgen-ai-6ec95',
    authDomain: 'reelgen-ai-6ec95.firebaseapp.com',
    storageBucket: 'reelgen-ai-6ec95.firebasestorage.app',
    measurementId: 'G-HSCG3WQKGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmzJo1o9QcKms7OxYt3cSt9zS1Av2C234',
    appId: '1:851061710789:android:b2375d2da8bf1b1a6535ac',
    messagingSenderId: '851061710789',
    projectId: 'reelgen-ai-6ec95',
    storageBucket: 'reelgen-ai-6ec95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYQr-sQuHLCYIEhslmVEUMy-uTnZtptLk',
    appId: '1:851061710789:ios:3c968e4135b6a6776535ac',
    messagingSenderId: '851061710789',
    projectId: 'reelgen-ai-6ec95',
    storageBucket: 'reelgen-ai-6ec95.firebasestorage.app',
    iosBundleId: 'com.example.reelGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYQr-sQuHLCYIEhslmVEUMy-uTnZtptLk',
    appId: '1:851061710789:ios:3c968e4135b6a6776535ac',
    messagingSenderId: '851061710789',
    projectId: 'reelgen-ai-6ec95',
    storageBucket: 'reelgen-ai-6ec95.firebasestorage.app',
    iosBundleId: 'com.example.reelGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNGK-dY8wrtuKenmD3gQTcqBzJn9_ssMk',
    appId: '1:851061710789:web:4f64614c7ea30dcb6535ac',
    messagingSenderId: '851061710789',
    projectId: 'reelgen-ai-6ec95',
    authDomain: 'reelgen-ai-6ec95.firebaseapp.com',
    storageBucket: 'reelgen-ai-6ec95.firebasestorage.app',
    measurementId: 'G-1K9D222G7Y',
  );
}
